// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateUserReq struct {
	Username  string            `json:"username"`
	Password  string            `json:"password"`
	Email     string            `json:"email,omitempty"`
	Extrainfo map[string]string `json:"extra_info,omitempty"`
}

type CreateUserResp struct {
	Uid int64 `json:"uid,string"`
}

type DeleteUserReq struct {
}

type DeleteUserResp struct {
	Success bool `json:"success"`
}

type GetUserReq struct {
}

type GetUserResp struct {
	User  UserInfo `json:"user,omitempty"`
	Found bool     `json:"found"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type LogoutReq struct {
}

type LogoutResp struct {
	Success bool `json:"success"`
}

type UpdateUserReq struct {
	Username  string            `json:"username,optional"`
	Password  string            `json:"password,optional"`
	Email     string            `json:"email,optional"`
	Extrainfo map[string]string `json:"extra_info,optional"`
}

type UpdateUserResp struct {
	User UserInfo `json:"user"`
}

type UploadAvatarReq struct {
	AvatarUrl   string `json:"avatar_url"`
	ContentType string `json:"content_type,optional"`
	SizeBytes   int64  `json:"size_bytes,optional"`
}

type AvatarHistoryItem struct {
	Id          string `json:"id"`
	AvatarUrl   string `json:"avatar_url"`
	ContentType string `json:"content_type"`
	SizeBytes   int64  `json:"size_bytes"`
	IsCurrent   bool   `json:"is_current"`
	CreateTime  string `json:"create_time"`
}

type UploadAvatarResp struct {
	AvatarUrl string            `json:"avatar_url"`
	History   AvatarHistoryItem `json:"history"`
}

type AvatarHistoryResp struct {
	List []AvatarHistoryItem `json:"list"`
}

type SelectAvatarReq struct {
	HistoryId string `json:"history_id"`
}

type SelectAvatarResp struct {
	AvatarUrl string            `json:"avatar_url"`
	History   AvatarHistoryItem `json:"history"`
}

type UserInfo struct {
	Uid       int64             `json:"uid,string"`
	Score     uint32            `json:"score"`
	Username  string            `json:"username"`
	Email     string            `json:"email,omitempty"`
	Extrainfo map[string]string `json:"extra_info,omitempty"`
}
